version: '3.4'

services:
  cache:
    image: redis:latest
  postegredb:
    image: postgres:latest
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Dockerfile
